 cHViIHN0YXRpYyBGRUFUVVJFX1hfRU5BQkxFRDogYm9vbCA9IHRydWU7ICAv
LyBUaGlzIGlzIHRoZSBmbGFnIHdlIHdhbnQgdG8gcmVtb3ZlIGxhdGVyCgpw
ewogICAgICAgIHByaW50bG4hKCJGZWF0dXJlIFggaXMgZW5hYmxlZCEiKTsK

The code related to the feature flag FEATURE_X_ENABLED has been removed.